name: issue-automation

on:
  issues:
    types: [opened]

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "Grant Status: (a) Application On Deck" # Replaced labels "Application Phase, Initial Review in Progress"
          repo-token: "${{ secrets.GH_TOKEN }}"
