name: "Set Issue Label and Assignee"
on:
  issues:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "body"
          parameters: '[ {"keywords": ["Open Source Dev 1st time Grantees"], "labels": ["Grant Type: Open Source Dev (First Time)"]}, {"keywords": ["Open Source Dev Repeat Grantees"], "labels": ["Grant Type: Open Source Dev (Repeat)"]}, {"keywords": ["Community Builder"], "labels": ["Grant Type: Stacks Community Builder Grant"]}, {"keywords": ["Education"], "labels": ["Grant Type: Stacks Education Grant"]}, {"keywords": ["Events"], "labels": ["Grant Type: Stacks Event Grant"]}, {"keywords": ["Chapter"], "labels": ["Grant Type: Stacks Chapter Grant"]}, {"keywords": ["ALEX Lab Foundation Grant"], "labels": ["Grant Type: Partner Grant (ALEX)"]}, {"keywords": ["Stacks Protocol"], "labels": ["Grant Track: Stacks Protocol"]}, {"keywords": ["Stacks Interface"], "labels": ["Grant Track: Stacks Interface"]}, {"keywords": ["Stacks dApps & Clarity"], "labels": ["Grant Track: Stacks dApps & Clarity"]}, {"keywords": ["Stacks Education & Community"], "labels": ["Grant Track: Community & Education"]}, {"keywords": ["Stacks Developer Experience"], "labels": ["Grant Track: Stacks Developer Experience"]}, {"keywords": ["Cross-Chain & Off-Chain"], "labels": ["Grant Track: Cross-Chain & Off-Chain"]}, {"keywords": ["Bitcoin Utility"], "labels": ["Bitcoin Utility via Stacks"]}]'
          github-token: "${{ secrets.GH_TOKEN }}"
