name: "Issue Column Change Label"
on:
  project_card:
    types:
      - moved
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: "Grantee Onboarding"
        uses: andymckay/labeler@master
        if: "${{ github.event.project_card.column_id == '19095931' }}"
        with:
          add-labels: 'Grant Status: (c) Grantee Onboarding'
          remove-labels: 'Grant Status: (a) Application On Deck, Grant Status: (b) Application in Review'
          repo-token: "${{ secrets.GH_TOKEN }}"
      - name: "Completing Final Deliverable"
        uses: andymckay/labeler@master
        if: "${{ github.event.project_card.column_id == '19095936' }}"
        with:
          add-labels: 'Grant Status: (d) Completing Initial Deliverable'
          remove-labels: 'Grant Status: (a) Application On Deck, Grant Status: (b) Application in Review, Grant Status: (c) Grantee Onboarding'
          repo-token: "${{ secrets.GH_TOKEN }}"
